#
# Makefile for SenseTek I2C sensors drivers.
#


obj-$(CONFIG_STK_ALS_220X_POLLING_MODE)		+= stk_i2c_als_220xgeneric.o
obj-$(CONFIG_STK_ALS22x7)		+= stk_i2c_als22x7.o
obj-$(CONFIG_STK_PS_DISTANCE_MODE)	+= stk_i2c_ps31xx_dist.o
obj-$(CONFIG_STK_PS_SWITCH_MODE)	+= stk_i2c_ps31xx_switch.o
obj-$(CONFIG_STK_PS_INT_MODE)		+= stk_i2c_ps31xx_int.o
obj-$(CONFIG_STK_GS_GENERIC)		+= stk_i2c_gs_generic.o
obj-$(CONFIG_STK_ALS_220X_INT_MODE)		+= stk_i2c_als_220x_int.o
